version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      # - run:
      #     name: Run Tests
      #     command: |
      #       . venv/bin/activate
      #       python manage.py test
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1 

  deploy:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: 
          name: Install Serverless
          command: |
            sudo yarn global add serverless
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Setup AWS Profile Permissions
          command: sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - run:
          name: Deploy
          command: sls deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
           - build
          filters:
            branches:
                only:
                - master
      - deploy:
          context: AWS
          requires:
            - hold
          # filters:
          #   branches:
          #     only:
          #       - master